# Generated by Django 4.0.3 on 2022-04-10 19:09

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('a_passenger', models.BooleanField(default=False, help_text='Determines whether the user is a passenger', verbose_name='passenger status')),
                ('an_airport_admin', models.BooleanField(default=False, help_text='Determines whether the user is an airport admin', verbose_name='airport admin status')),
                ('an_airline_admin', models.BooleanField(default=False, help_text='Determines whether the user is an airline admin', verbose_name='airline admin status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'airline',
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('economy_seats', models.PositiveIntegerField()),
                ('premium_economy_seats', models.PositiveIntegerField()),
                ('business_seats', models.PositiveIntegerField()),
                ('first_seats', models.PositiveIntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='api.airline')),
            ],
            options={
                'db_table': 'airplane',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('airport_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='hotel_images/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='api.company')),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='AirlineAdmin',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='airline_admin', serialize=False, to=settings.AUTH_USER_MODEL, to_field='email')),
                ('employee_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'airline_admin',
            },
        ),
        migrations.CreateModel(
            name='AirportAdmin',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='airport_admin', serialize=False, to=settings.AUTH_USER_MODEL, to_field='email')),
                ('admin_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'db_table': 'airport_admin',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='passenger', serialize=False, to=settings.AUTH_USER_MODEL, to_field='email')),
                ('ssn', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.company')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.passenger')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='stay_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stay_images/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='api.hotel')),
                ('transac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays', to='api.transaction')),
            ],
            options={
                'db_table': 'stay',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.airline')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='api.destination')),
                ('plane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='api.airplane')),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cabin', models.CharField(max_length=255)),
                ('tickets_quantity', models.PositiveIntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='api.flight')),
            ],
            options={
                'db_table': 'fare',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_pos', models.CharField(max_length=255)),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.fare')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='api.passenger')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='api.airportadmin'),
        ),
        migrations.CreateModel(
            name='AirportComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airport_complaints', to='api.airportadmin')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_complaints', to='api.passenger')),
            ],
            options={
                'db_table': 'airport_complaint',
            },
        ),
        migrations.CreateModel(
            name='AirlineComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_complaints', to='api.airline')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airline_complaints', to='api.airlineadmin')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_complaints', to='api.passenger')),
            ],
            options={
                'db_table': 'airline_complaint',
            },
        ),
    ]
