# Generated by Django 4.0.3 on 2022-04-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airlinecomplaint',
            old_name='a_email',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='airlinecomplaint',
            old_name='p_email',
            new_name='passenger',
        ),
        migrations.RenameField(
            model_name='airportcomplaint',
            old_name='a_email',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='airportcomplaint',
            old_name='p_email',
            new_name='passenger',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='a_email',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='plane_id',
            new_name='plane',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='transac_id',
            new_name='transac',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='fare_id',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='p_email',
            new_name='passenger',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='p_email',
            new_name='passenger',
        ),
    ]
