# Generated by Django 4.0.3 on 2022-04-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_pos',
        ),
    ]
