# Generated by Django 4.0.3 on 2022-04-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='dest',
            new_name='destination',
        ),
    ]
