# Generated by Django 4.0.3 on 2022-04-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airlinecomplaint',
            old_name='airline_name',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='airplane',
            old_name='airline_name',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='fare',
            old_name='flight_num',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airline_name',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='dest_code',
            new_name='dest',
        ),
    ]
